---
apiVersion: v1
kind: Service
metadata:
  name: crm-six-network
  namespace: graphic
spec:
  ports:
  - port: 80
    targetPort: 80
    name: "80"
    nodePort: 32492
  type: NodePort
  selector:
    app: crm-six-network
