const admin = require('firebase-admin');
const uuid = require('uuid/v5');
const configPath = __dirname + '/config/config.json';
const serviceAccount = require(configPath);

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://sixdashboard.firebaseio.com',
});
const db = admin.firestore();

async function getUIDByEmail(email) {
  return admin
    .auth()
    .getUserByEmail(email)
    .then(userRecord => userRecord.uid)
    .catch(() => false);
}

emails = [
  'bkchoi@yellomobile.com',
  'bjjong@fsn.co.kr',
  'ykikicom@gmail.com',
  'ldy@adqua.co.kr',
  'dhkim@adqua.co.kr',
  'thinkership@adqua.co.kr',
  'until99@gmail.com',
  'chc@adqua.co.kr',
  'head@motherbrain.co.kr',
  'bl0323@adqua.co.kr',
  'jihoons@fsn.co.kr',
  'jjy7942@hanmail.net',
  'jeundyj@daum.net',
  'junelee@adqua.co.kr',
  'adored0@naver.com',
  'mike.hwang@recobell.com',
  'onlymr@adqua.co.kr',
  'dalnorae@groupidd.com',
  'hamans@hanmail.net﻿',
  'sagac@daum.net',
  'shlee@yellomobile.com',
  'sslee@yellomobile.com',
  'fromp@adqua.co.kr',
  'seungho.lee@yellomobile.com',
  'june@adqua.co.kr',
  'chonju2002@naver.com',
  'ysook@groupidd.com',
  'kurt@groupidd.com',
  'loveme610@motherbrain.co.kr',
  'smpark@adqua.co.kr ',
  'remeet@ydmbuzz.com',
  'arak.sutivong@gmail.com',
  'ojazzy@gmail.com',
  'bhurit@boonrawd.co.th',
  'nuttapong.tc@gmail.com',
  'charkrid@gmail.com',
  'charn@taamkru.com',
  'harpremdoowa@gmail.com',
  'pattawan.j@taokaenoi.co.th',
  'tulyanond@gmail.com',
  'khailee@500.co',
  'sudatip.piyavee@gmail.com',
  'nbhirombhakdi213@gmail.com',
  'nintita@smartcoating.com',
  'pippo41@gmail.com',
  'natthakit.susanthitanon@gmail.com',
  'suthijoe@gmail.com',
  'buffalo660@gmail.com',
  'sukumwhut@gmail.com',
  'nraktaprachit@gmail.com',
  'naphat12@hotmail.com',
  'settaporn.s@gmail.com',
  'teenoybu2@gmail.com',
  'sarun@fungjai.com',
  'ricky@nvk.co.th',
  'polapat@ookbee.com',
  'alaaum@hotmail.com',
  'cprapon@gmail.com',
  'iphong@uw.edu',
  'safefy@gmail.com',
  'siwat.tee34@gmail.com',
  'wasita.ra135@gmail.com',
  'genatorster@gmail.com',
  'bee4000@hotmail.com',
  'ooknew55@gmail.com',
  'sahmzheii@gmail.com',
  'uuu.naja@gmail.com',
  'divinitysex@gmail.com',
  'passakorn.sub@gmail.com',
  'yellowisdad@gmail.com',
  'fireboat999@hotmail.com',
  'arokung@gmail.com',
  'note@ookbee.com',
  'vasupol@ookbee.com',
  'pattanan.bp@gmail.com',
  'ekamorn.012@gmail.com',
  'dorracha.ch@gmail.com',
  'iprewlome@gmail.com',
  'chromogafee@gmail.com',
  'korakot@ookbee.com',
  'padthamapp@gmail.com',
  'laddawanna@gmail.com',
  'chareef17@gmail.com',
  'screening1@gmail.com',
  'nattipat@ookbee.com',
  'bebick@hotmail.com',
  'lps.j18@gmail.com',
  'karnraweewong@gmail.com',
  'warakorn9z@gmail.com',
  'piyanggoon93@gmail.com',
  'sarawee_b@hotmail.com',
  'natchyyyy@gmail.com',
  'chaiyasit.u@gmail.com',
  'top_tap@msn.com',
  'chinnapat.b@gmail.com',
  'nrongsakdi@gmail.com',
  'kanjana.ji@yahoo.com',
  'pianp.jsw@gmail.com',
  'phannisa.hs@gmail.com',
  'chawapol@cmg.co.th',
  'r.muangkroot@gmail.com',
  'kratingp@gmail.com',
  'ceo@mfec.co.th',
  'tsudchai@gmail.com',
  'tim.chae@gmail.com',
  'sompoat@icloud.com',
  'dimpleart@gmail.com',
  'chawisa.chen@gmail.com',
  'vorapat_c@boonrawd.co.th',
  'voraphun.t@gmail.com',
  'warokart@gmail.com',
  'ariya.banomyong@gmail.com',
  'vchavana@gmail.com',
  'chatchaik@gmail.com',
  'avudh.ploy@gmail.com ',
  'k.atcharakitti@gmail.com',
  'pongsatorn@g-tem.com',
  'tplim@pacrimgroup.com',
  'porntip@pacrimgroup.com',
  'd_ladawan@doublea1991.com',
  'yos.ginting@gmail.com ',
  'kawayanagik@hotmail.com',
  'wongchindawest@gmail.com ',
  'swc4007@gmail.com',
  'ekarin.th@gmail.com',
  'polapat@gmail.com',
  'natavudh@gmail.com',
  'sangboon@gmail.com',
  'mig09@hotmail.com',
  'pakpoom.s@gmail.com',
  'imchoi@gmail.com',
  'sam.tanskul@yahoo.com',
  'thanahappymail@gmail.com',
  'thanapong.na@gmail.com',
  'vachara@six.network',
  'vachara@computerlogy.com',
  'tanapon@adyim.com',
  'itthi.yossundara@gmail.com',
  'watcharapong@six.network',
  'ayoungh@gmail.com',
  'brian@formationgroup.com',
  'chcho@fsn.co.kr',
  'donaldck@fsn.co.kr',
  'andy.chiwon.kim@gmail.com',
  'first030@yellomobile.com',
  'dkchang@yellostory.co.kr',
  'pabijoa2@naver.com',
  'rudtlr1098@hanmail.net',
  'jin7370@gmail.com',
  'tonyhong1004@naver.com',
  'lon2001@hanmail.net',
  'inhwanc@gmail.com',
  'nonesmoking@naver.com',
  'jkh9336@gmail.com',
  'zephaniah@naver.com',
  'eun289k@gmail.com',
  'angelcee@naver.com',
  'noamsaid@gmail.com',
  'slhlove333@naver.com',
  'helper@madsq.net',
  'jooyi.kang@gmail.com',
  'happyjuhwa@naver.com',
  'jungwoo.jang@hotmail.com',
  'jungdonoh.apply@gmail.com',
  'jaysuk@yellomobile.com',
  'kman0204@naver.com',
  'knamjin@ysmcorp.com',
  'kim.kishik@gmail.com',
  'angus_kim@naver.com',
  'andrewleekr@naver.com',
  'crossover3737@gmail.com',
  'jonlee@yellomobile.com',
  'kimnamchul@daum.net',
  'neochg@naver.com',
  'lae@formationgroup.com',
  'sh.ahn@daylifg.com',
  'john.sejunkim@gmail.com',
  'seanshs@naver.com',
  'sijung00@gmail.com',
  'david.baik@groupidd.com',
  'cordiallys@gmail.com',
  'ryoosunghoon@naver.com',
  'ssshwan@naver.com',
  'sunghyuk.dave.park@gmail.com',
  'sfkim@yellomobile.com',
  'remeet@naver.com',
  'yjung@yellostory.co.kr',
  'airboom77@hanmail.net',
  'starbae@gmail.com',
  'das412@hanmail.net',
  'natavudh@six.network',
  'moo@ookbee.com',
  'bradshin@fsn.co.kr',
  'andrew@yellomobile.com',
  'leo@ad-max.co.kr',
  'smpark@adqua.co.kr',
  'peter@mediance.co.kr',
  'sykim@yellostory.co.kr',
  'dave.park@recobell.com',
  'sunnhlee@hanmail.net',
  'ha501136@gmail.com',
  '01692216665@naver.com',
  'suchada@favstay.com ',
  'dk@blueblock.co  ',
  'saber.aria@gmail.com ',
  'joon8129@gmail.com',
  'ys.shin@intervest.co.kr',
  'sangboon@itworks.co.th',
  'morikawa@cchan.tv',
  'swc4007@gmail.com ',
  'jonlee@yellomobile.com ',
  'khailee@500.co ',
  'korn.chatikavanij@gmail.com ',
  'min.kim@daylifg.com',
  'phawit.chi@gmmgrammy.com',
  'kratingp@gmail.com ',
  'ceo@mfec.co.th ',
  'thakorn.piyapan@krungsri.com ',
  'thanahappymail@gmail.com ',
  'thanapong.na@gmail.com ',
  'vincent.ha@gushcloud.com ',
  'jirath@ignite.co.th',
  'imchoi@gmail.com ',
  'siwat@siwat.com',
  'knamjin@yellomobile.com',
  'daylifinancial@daylifg.com',
  'charkrid@six.network',
  'nisanart@six.network',
];

emails.forEach(async email => {
  const uid = await getUIDByEmail(email.trim());
  if (uid) return;
  console.log(email);
});
